feedreader/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
from feedreader.api import UserResource

admin.autodiscover()

user_resource = UserResource()

urlpatterns = patterns('',
    url(r'^email/register/', 'pin.views.email_register', name='email_register'),
    url(r'^pass/reset/', 'pin.views.pass_reset', name='pass_reset'),
    url(r'^newsletter/', 'pin.views.newsletter', name='newsletter'),
    url(r'^notification/$', 'pin.views_user.user_notif', name="user-notif"),

    url(r'^$', 'pin.views.home', name='home'),
    # url(r'^latest_post/', 'latest_redis', name='pin-latest-old'),
    url(r'^profile/', include('user_profile.urls')),
    url(r'^pin/', include('pin.urls')),
    # url(r'^feedback/', include('contactus.urls')),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    # url(r'', include('social_auth.urls')),
    # url(r'^acc/', include('allauth.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^pages/', include('django.contrib.flatpages.urls')),
    url(r'^api/', include(user_resource.urls)),
    url(r'^policy/', 'pin.views.policy', name='policy'),
    url(r'^policy_for_mobile/', 'pin.views.policy_for_mobile', name='policy_for_mobile'),
    url(r'^about_us/', 'pin.views.about_us', name='about_us'),
    url(r'^about_us_for_mobile/', 'pin.views.about_us_for_mobile', name='about_us_for_mobile'),
    url(r'^stats/', 'pin.views.stats', name='stats'),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^buggy/', 'pin.views_test.buggy', name='buggy'),
    url(r'^api/v6/', include('pin.api6.urls')),
    url(r'^dashboard/', include('pin.views2.dashboard.urls')),
    url(r'^angular/', include('pin.views2.angular.urls')),
    url(r'^shop/', include('shop.urls')),
)

urlpatterns += patterns('pin.views',
    url(r'^latest/$', 'latest', name='pin-latest'),
    url(r'^page/(?P<label>.*)/$', 'result', name='pin-result'),
    url(r'^feedback/$', 'feedback', name='pin-feedback'),

    url(r'^category/(?P<cat_id>\d+)/$', 'category', name='pin-category'),
    url(r'^category/(?P<category_id>\d+)/top/$', 'category_top', name='pin-category-top'),

    url(r'^search/', 'search', name='search'),
    url(r'^tag/(?P<tag_name>.*)/$', 'tags', name='tags'),
    url(r'^hashtag/(?P<tag_name>.*)/$', 'hashtag', name='hashtags'),

    url(r'^user/(?P<user_id>\d+)/$', 'user', name='pin-user'),
    url(r'^user/(?P<user_id>\d+)/likes/$', 'user_like', name='pin-user-like'),
    url(r'^user/(?P<user_id>\d+)/friends/$', 'user_friends', name='pin-user-friends'),
    url(r'^user/(?P<user_id>\d+)/following/$', 'user_friends', name='pin-user-following'),
    url(r'^user/(?P<user_id>\d+)/followers/$', 'user_followers', name='pin-user-followers'),

    url(r'^popular/(?P<interval>\w+)/$', 'popular', name='pin-popular-offset'),
    url(r'^popular/', 'popular', name="pin-popular"),
    url(r'^top/user/all/$', 'topuser', name='pin-topuser'),
    url(r'^top/user/monthly/$', 'leaderboard', name='pin-topmonthgroup'),
    url(r'^top/user/groups/$', 'topgroupuser', name='pin-topgroupuser'),
)

urlpatterns += patterns('pin.views3_api',
    url(r'^api/v3/post/latest/$', 'post_latest', name="api-3-latest"),
    url(r'^api/v3/post/item/(?P<post_id>\d+)/$', 'post_item', name="api-3-item"),
)

urlpatterns += patterns('pin.views4_api',
    url(r'^api/v4/user/blockers/$', 'user_blockers', name="api-4-blockers"),
    url(r'^api/v4/user/blocked/$', 'user_blocked', name="api-4-blocked"),
    url(r'^api/v4/user/near_by/$', 'user_near_by', name="api-4-nearby"),
    url(r'^api/v4/user/register/$', 'register', name="api-4-register"),
    url(r'^api/v4/user/block/$', 'block_user', name="api-4-block"),
    url(r'^api/v4/user/unblock/$', 'unblock_user', name="api-4-unblock"),
    url(r'^api/v4/user/follow/$', 'follow', name="api-4-follow"),
    url(r'^api/v4/user/unfollow/$', 'unfollow', name="api-4-unfollow"),
    url(r'^api/v4/user/credit/$', 'user_credit', name="api-4-user-credit"),
    url(r'^api/v4/user/check/username/$', 'user_check_username', name="api-4-user-check-username"),

)

if not settings.DEBUG:
    urlpatterns += patterns('pin.views',
        url(r'^(?P<user_namefl>.*)/followers/$', 'absuser_followers', name='pin-absuser-followers'),
        url(r'^(?P<user_namefg>.*)/following/$', 'absuser_following', name='pin-absuser-following'),
        url(r'^(?P<user_namel>.*)/likes/$', 'absuser_like', name='pin-absuser-like'),
        url(r'^(?P<user_name>.*)/$', 'absuser', name='pin-absuser'),
    )

pin/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from pin.feeds import EditorPinFeed
from pin.api import PostResource, CategotyResource, CommentResource,\
    ProfileResource, AppResource, StreamResource

admin.autodiscover()

post_resource = PostResource()
cat_resource = CategotyResource()
comment_resource = CommentResource()

profile_resource = ProfileResource()
app_resource = AppResource()

stream_resource = StreamResource()


urlpatterns = patterns('pin.views',
    url(r'^$', 'home', name='pin-home'),
    url(r'^search/', 'search', name='search'),
    url(r'^(?P<item_id>\d+)/$', 'item', name="pin-item"),
    url(r'^(?P<item_id>\d+)/related/$', 'item_related', name="pin-item-related"),
    url(r'^user/(?P<user_id>\d+)/likes/$', 'user_like', name='pin-user-like'),
    url(r'^user/(?P<user_id>\d+)/friends/$', 'user_friends', name='pin-user-friends'),
    url(r'^user/(?P<user_id>\d+)/following/$', 'user_friends', name='pin-user-following'),
    url(r'^user/(?P<user_id>\d+)/followers/$', 'user_followers', name='pin-user-followers'),
    url(r'^user/(?P<user_id>\d+)/$', 'user', name='pin-user'),
    url(r'^user/(?P<user_id>\d+)/(?P<user_name>\w+)/$', 'user', name='pin-user-new'),
    url(r'^likers/(?P<post_id>\d+)/(?P<offset>\d+)/$', 'post_likers', name='pin-likers'),
    url(r'^likers/(?P<post_id>\d+)/$', 'post_likers', name='pin-likers'),

    url(r'^com/posts/(?P<post_id>\d+)/', 'get_comments', name='pin-get-comments'),
    url(r'^editor/choices/feed/', EditorPinFeed(), name="pin-latest-feed"),

    url(r'^popular/(?P<interval>\w+)/$', 'popular', name='pin-popular-offset'),
    url(r'^popular/', 'popular', name="pin-popular"),
    url(r'^topuser/$', 'topuser', name='pin-topuser'),
    url(r'^top-group-user/$', 'topgroupuser', name='pin-topgroupuser'),

    url(r'^category/(?P<cat_id>\d+)', 'category', name='pin-category'),

    url(r'^api1/', include(post_resource.urls)),
    url(r'^apic/', include(cat_resource.urls)),
    url(r'^api/profile/', include(profile_resource.urls)),
    url(r'^api/app/', include(app_resource.urls)),
    url(r'^api/stream/', include(stream_resource.urls)),
)

urlpatterns += patterns('pin.views_user',
    url(r'^notif/$', 'notif_user', name="pin-notif-user"),
    url(r'^following/activity/$', 'notif_following', name="pin-notif-user-following"),
    url(r'^notif/all/$', 'notif_all', name="pin-notif-user-all"),
    url(r'^like/(?P<item_id>\d+)', 'like', name="pin-item-like"),
    url(r'^following/$', 'following', name='pin-following'),
    url(r'^follow/$', 'follow', name='pin-follow'),
    url(r'^follow/(?P<following>\d+)/(?P<action>\d+)/$', 'follow', name='pin-follow'),
    url(r'^send_comment/', 'send_comment', name='pin-comment'),
    url(r'^comment/score/(?P<comment_id>\d+)/(?P<score>\d+)', 'comment_score', name="pin-comment-score"),
    url(r'^show_notify/', 'show_notify', name="show_notify"),
    url(r'^you_are_deactive', 'you_are_deactive', name='pin-you-are-deactive'),
    url(r'^report/(?P<pin_id>\d+)', 'report', name='report_pin'),
    url(r'^delete/(?P<item_id>\d+)', 'delete', name="pin-item-delete"),
    url(r'^nop/(?P<item_id>\d+)', 'nop', name="pin-item-nop"),
    url(r'^ajax_upload/$', 'upload', name="pin-upload"),
    url(r'^ajax_url/$', 'a_sendurl', name="pin-sendurl-a"),
    url(r'^edit/(?P<post_id>\d+)/$', 'edit', name="pin-item-edit"),
    url(r'^sendurl/$', 'sendurl', name="pin-sendurl"),
    url(r'^send/$', 'send', name="pin-send"),
    url(r'^inc/credit/$', 'inc_credit', name="pin-inc-credit"),
    url(r'^verify_payment/(?P<bill_id>\w+)/$', 'verify_payment', name="pin-verify-payment"),
    url(r'^save/as/ads/(?P<post_id>\w+)/$', 'save_as_ads', name="pin-save-as-ads"),
    url(r'^user/action/(?P<user_id>\d+)/$', 'block_action', name="pin-user-block"),
    url(r'^blocked/$', 'blocked_list', name="blocked-list"),
    url(r'^promotion/$', 'promotion_list', name="promotion-list"),
)

# urlpatterns += patterns('pin.views_backbone',
#     url(r'new/home', 'home', name='new-home'),
#     url(r'new/notif/', 'notif', name='new-notif'),
# )

urlpatterns += patterns('pin.views_oauth',
    url(r'invite/google', 'invite_google', name='invite-google'),
    url(r'email/activation/$', 'activation_email', name='activation_email'),
)

# urlpatterns += patterns('pin.views_static',
#     url(r'app/android/', 'android', name='static-android'),
# )

urlpatterns += patterns('pin.views_admin',
    url(r'user/activate/(?P<user_id>\d+)/(?P<status>\d+)/$', 'activate_user', name='activate-user'),
    url(r'^goto_index/(?P<item_id>\d+)/(?P<status>\d+)/', 'goto_index', name='pin-item-goto-index'),

    url(r'^comment/delete/(?P<id>\d+)', 'comment_delete', name="pin-comment-delete"),
)

urlpatterns += patterns('pin.views_device',
    url(r'^d_send/$', 'post_send', name="pin-direct"),
    url(r'^d_like/$', 'like', name='pin-device-like'),
    url(r'^d_post_comment/$', 'post_comment', name='pin-device-post-comment'),
    url(r'^d_post_report/$', 'post_report'),
    url(r'^d/comment/score/(?P<comment_id>\d+)/(?P<score>\d+)/$', 'comment_score'),
    url(r'^d/post/delete/(?P<item_id>\d+)/$', 'post_delete'),
    url(r'^d/post/update/(?P<item_id>\d+)/$', 'post_update'),
    url(r'^d/comment/report/(?P<comment_id>\d+)/$', 'comment_report'),
    url(r'^d/follow/(?P<following>\d+)/(?P<action>\d+)/$', 'follow'),

)

urlpatterns += patterns('',
    url(r'^api/post/(?P<item_id>\d+)/$', 'pin.views2_api.post_item', name="post_api_item"),
    url(r'^api/post/(?P<post_id>\d+)/details/', 'pin.views2_api.post_details', name="post_api_details"),
    url(r'^api/post/', 'pin.views2_api.post', name="post_api"),
    url(r'^api/post2/', 'pin.views2_api.post2', name="post_api2"),
    url(r'^api/promoted/post/', 'pin.views2_api.promoted', name="promoted_api"),
    url(r'^api/hashtag/$', 'pin.views2_api.hashtag', name="api-hashtag"),
    url(r'^api/hashtag/top/$', 'pin.views2_api.hashtag_top', name="api-hashtag-top"),
    url(r'^api/com/comments/', 'pin.views2_api.comments', name="api_comments"),
    url(r'^api/friends_post/', 'pin.views2_api.friends_post', name="post_friends_api"),
    url(r'^api/like/likes/', 'pin.views2_api.likes', name="likes_api"),
    url(r'^api/notif/notify/$', 'pin.views2_api.notif', name="new_notif"),
    url(r'^api/notif/count/$', 'pin.views2_api.notif_count', name="new_notif_count"),
    url(r'^api/comment/delete/(?P<id>\d+)/$', 'pin.views2_api.comment_delete', name="new_comment_delete"),

    url(r'^api/following/(?P<user_id>\d+)/', 'pin.views2_api.following', name="api-following"),
    url(r'^api/follower/(?P<user_id>\d+)/', 'pin.views2_api.follower', name="api-follower"),
    url(r'^api/search/$', 'pin.views2_api.search', name="api-search"),
    url(r'^api/v2/search/$', 'pin.views2_api.search2', name="api-search-v2"),

    url(r'^api/search/posts/$', 'pin.views2_api.search_posts', name="api-search-posts"),
    url(r'^api/system/$', 'pin.views2_api.system', name="api-system"),

    url(r'^api/block/user/(?P<user_id>\d+)/', 'pin.views2_api.block_user', name="api-block"),
    url(r'^api/unblock/user/(?P<user_id>\d+)/', 'pin.views2_api.unblock_user', name="api-block"),

    url(r'^api/packages/$', 'pin.views2_api.packages_old', name="api-packages_old"),
    url(r'^api/packages2/$', 'pin.views2_api.packages', name="api-packages"),

    url(r'^api/promotion/prices/$', 'pin.views2_api.promotion_prices', name="api-promotion-prices"),
    url(r'^api/user/credit/$', 'pin.views2_api.user_credit', name="api-user-credit"),
    url(r'^api/user/inc/credit/$', 'pin.views2_api.inc_credit', name="api-user-inc-credit"),

    url(r'^api/save/as/ads/(?P<post_id>\d+)/$', 'pin.views2_api.save_as_ads', name="api-save-as-ads"),

    url(r'^api/gcm/get/phone/data/$', 'pin.views2_api.get_phone_data', name="api-get-phone-data"),
    url(r'^api/plus/get/data/$', 'pin.views2_api.get_plus_data', name="api-get-phone-data"),
    url(r'^api/logout/$', 'pin.views2_api.logout', name="api-logout"),

    url(r'^api/password/reset_mobile/$', 'pin.views2_api.password_reset',
        name='api_password_reset'),

    url(r'^api/password/change_mobile/$', 'pin.views2_api.change_password',
        name='password_change_mobile'),
)

user_profile/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('user_profile.views',
    # Examples:
    url(r'^change/$', 'change', name="user-profile-change"),
    url(r'^d_change/$', 'd_change', name="device-user-profile-change"),
)

shop/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.conf import settings

# from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _


class Category(models.Model):
    name = models.CharField(max_length=150)
    text = models.TextField()

    def __unicode__(self):
        return self.name


class Product(models.Model):
    X1 = 1
    X2 = 2
    H2 = 3
    X2H2 = 4

    MODES = (
        (X1, "normal"),
        (X2, "x2"),
        (H2, "H2"),
        (X2H2, "X2H2"),
    )
    title = models.CharField(max_length=250)
    title_en = models.CharField(max_length=250, blank=True, default="")
    description = models.TextField()
    price = models.IntegerField(default=0)
    in_stock = models.BooleanField(default=True)
    in_home = models.BooleanField(default=False)
    sort = models.IntegerField(default=0)

    mode = models.IntegerField(choices=MODES, default=X1)

    category = models.ForeignKey(Category)

    def __unicode__(self):
        return self.title

    def delete(self, *args, **kwargs):
        super(Product, self).delete(*args, **kwargs)


class ProductImages(models.Model):
    image = models.ImageField(upload_to="product")
    primary = models.BooleanField(default=False)
    product = models.ForeignKey(Product, related_name="images")

    def delete(self, *args, **kwargs):
        storage, path = self.image.storage, self.image.path
        super(ProductImages, self).delete(*args, **kwargs)
        storage.delete(path)


class Cart(models.Model):
    quantity = models.IntegerField(default=1)
    product = models.ForeignKey(Product)
    user = models.ForeignKey(settings.AUTH_USER_MODEL)


class Recivers(models.Model):
    full_name = models.CharField(max_length=300)
    address = models.TextField()
    phone = models.CharField(max_length=50)
    postal_code = models.CharField(max_length=100)

    user = models.ForeignKey(settings.AUTH_USER_MODEL)


class Order(models.Model):
    CHECKING = 1
    ACCEPTED = 2
    PREPAIRING = 3
    SENT = 4
    RECIVED = 5

    STATUS = (
        (CHECKING, _("Pending")),
        (ACCEPTED, _("Accepted")),
        (PREPAIRING, _("Preparation")),
        (SENT, _("Sent")),
        (RECIVED, _("Recived")),
    )

    product = models.ForeignKey(Product)
    quantity = models.IntegerField(default=1)
    status = models.IntegerField(choices=STATUS, default=CHECKING)

    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    reciver = models.ForeignKey(Recivers)


# class HesabitToken(models.Model):
#     token = models.CharField(max_length=255, null=True, blank=True)
#     refresh_token = models.CharField(max_length=255, null=True, blank=True)
#     expire_time = models.IntegerField(default=10 * 3600)
#     create_at = models.DateTimeField(auto_now=True)
#     user = models.ForeignKey(settings.AUTH_USER_MODEL)

user_profile/forms.py
from user_profile.models import Profile
from django.forms import ModelForm


class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ('name', 'location', 'website', 'bio', 'avatar', 'jens')


class ProfileForm2(ModelForm):
    class Meta:
        model = Profile
        fields = ('name', 'location', 'website', 'bio', 'avatar', 'jens', 'cover')

user_profile/templates/__change.html
{% load widget_tweaks %}
{{form.errors}}
<form class="form-horizontal profile_change" method="post" enctype="multipart/form-data" action="{% url "user-profile-change"%}">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">تغییر مشخصات کاربری</h4>
    </div>
    <div class="modal-body ma10">

        {% csrf_token %}
        <div class="avatar_box row">
            <div class="">
                <div class="current_avatar col-sm-6">
                    <h4>آواتار فعلی:</h4>
                    <img class="img img-circle" id="avatar_img" src="{{MEDIA_URL}}{{user.profile.avatar}}" alt="">

                    <div class="hide">
                        <h4>آواتار جدید</h4>
                        <div class="new_avatar"></div>
                        <a href="javascript:;" class="wis_btn save_crop">ذخیره</a>
                    </div>

                </div>
                <div class="avatar_crop col-sm-6">
                    <h4>تغییر آواتار:</h4>
                    <img src="{{MEDIA_URL}}v2/images/upload_img.png" class="upload_img_btn" alt="">
                    <div class="clear"></div>
                    <div class="old_content">
                        <div class="mato20"></div>
                        <input id="avatar-clear_id" type="checkbox" name="avatar-clear">
                        <label for="avatar-clear_id">پاک کردن</label>
                        <input id="id_avatar" type="file" name="avatar">

                        {% comment %}
                        {% render_field form.avatar %}
                        {% endcomment %}
                    </div>
                </div>
            </div>
        </div>
        <div class="clear"></div>

        <div class="row">
            <div class="col-sm-6 pull-right">
                <label class="control-label" for="">{{form.name.label}}</label>
                <div>
                    <input id="id_name" class="form-control" type="text" name="name" value="{{form.name.value|default_if_none:" "}}" maxlength="250" />
                </div>
            </div>
            <div class="col-sm-6 pull-right">
                <label class="control-label" for="">جنسیت</label>
                <div>
                    {% render_field form.jens class+="form-control" %}
                </div>
            </div>
        </div>
        <div class="clear"></div>

        <div class="row">
            <div class="col-sm-6">
                <label class="control-label" for="">{{form.location.label}}</label>
                <div class="">
                    <input id="id_location" type="text" class="form-control" name="location" value="{{form.location.value|default_if_none:" "}}" maxlength="250" />
                </div>
            </div>
        </div>
        <div class="clear"></div>

        <div class="row">
            <div class="col-sm-12">
                <label class="control-label" for="">{{form.website.label}}</label>
                <div>
                    <input id="id_website" class="form-control ltr" type="text" name="website" value="{{form.website.value|default_if_none:" "}}" maxlength="200" />
                </div>
            </div>
        </div>
        <div class="clear"></div>

        <div class="row">
            <div class="col-sm-12">
                <label class="control-label" for="">{{form.bio.label}}</label>
                <div>
                    <textarea id="id_bio" class="form-control" name="bio">{{form.bio.value|default_if_none:""}}</textarea>
                </div>
            </div>
        </div>
        <div class="clear"></div>

    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">انصراف</button>
        <button type="submit" class="btn btn-primary">بروز رسانی</button>
    </div>
</form>

<!-- Crop Modal -->
<div class="modal fade" id="cropModal" tabindex="-1" role="dialog" aria-labelledby="cropModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close close_crop"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="cropModalLabel">برش تصویر</h4>
            </div>
            <div class="modal-body dl">
                <div class="crop_modal_content"></div>
            </div>
            <div class="modal-footer">
                <a href="javascript:;" class="wis_btn save_crop">ذخیره</a>
            </div>
        </div>
    </div>
</div>

user_profile/templates/change.html
{% extends "pin2/flat.base.box.html" %}

{% block content %}
<div class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            {% include "__change.html" %}
        </div>
    </div>
</div>

{% endblock %}